

DATA:
  data_path: /Users/davidsewell/MLData/
  load_watch:
    accel: true
    gyro: false
  load_phone:
    accel: false
    gyro: false
  load_all: true
  load_subjects: [1600,1601]
  #load_subjects: [1600,1601,1602,1603,1604,1605,1606,1607,1608,1609]
  #load_subjects: [1605,1606,1607,1608,1609]

TRANSFORM:
  features: [] # put features in order of desired application

MODEL:
  model_name:
    params:

OUTPUT:
  output_path: